service: softtek-ts
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:822235993083:table/PeopleTable

functions:
  welcome:
    handler: src/lambdas/welcome.hello
    events:
      - httpApi: GET /
  swapiAllPeople:
    handler: src/lambdas/swapi/people/allPeople.allPeople
    events:
      - httpApi: GET /swapi/people
  swapiGetPeople:
    handler: src/lambdas/swapi/people/getPeople.getPeople
    events:
      - httpApi: GET /swapi/people/{id}
  allPeople:
    handler: src/lambdas/people/allPeople.allPeople
    events:
      - httpApi: GET /people
  createPeople:
    handler: src/lambdas/people/addPeople.addPeople
    events:
      - httpApi:
          method: POST
          path: /people

resources:
  Resources:
    PeopleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PeopleTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-esbuild
  - serverless-offline