service: softtek-ts
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    DYNAMODB_TABLE: 'PeopleTable'
  region: us-east-1
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"

functions:
  welcome:
    handler: src/lambdas/welcome.hello
    events:
      - httpApi: GET /
  swapiAllPeople:
    handler: src/lambdas/swapi/people/allPeople.allPeople
    events:
      - httpApi: GET /swapi/people
  swapiGetPeople:
    handler: src/lambdas/swapi/people/getPeople.getPeople
    events:
      - httpApi: GET /swapi/people/{id}
  allPeople:
    handler: src/lambdas/people/allPeople.allPeople
    events:
      - httpApi: GET /people
  createPeople:
    handler: src/lambdas/people/addPeople.addPeople
    events:
      - httpApi:
          method: POST
          path: /people

resources:
  Resources:
    PeopleTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-esbuild
  - serverless-offline